# 토큰 발급 API
GET localhost:3000/token/waiting-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTcyMTU0OTYyNCwiZXhwIjoxNzIxNTU2ODI0fQ.xXYchT_xUFmS2uDvXbSWy4U3v_NrDt83IW08YQJBWWY
